testing things

diff --git a/.github/workflows/test-workflow.yml b/.github/workflows/test-workflow.yml
--- a/.github/workflows/test-workflow.yml
+++ b/.github/workflows/test-workflow.yml
@@ -14,7 +14,7 @@ jobs:
         run: |
           echo "Running Step 1"
           sleep 30
-      # - run: exit 1 # force test failure
+      - run: exit 1 # force test failure
 
   job-2:
     runs-on: ubuntu-latest
@@ -72,11 +72,10 @@ jobs:
             slack_token: ${{ secrets.SLACK_TOKEN }}
             slack_channel: "U07KNKY6S5C"
             notify_on: "always"
-            filter_jobs: "job-1,e2e-test-1"
-            # include_job_statuses: 'on-failure'
-            # comment_junit_failures: "true"
-            # comment_junit_flakes: "true"
-            # custom_title: "Testing my own comment title. <https://example.com|A link.>"
+            filter_jobs: "job-1,job-2,e2e-test-1"
+            comment_junit_failures: "true"
+            comment_junit_flakes: "true"
+            custom_title: "Testing my own comment title. <https://example.com|A link.>"
 
   slack-notify-never:
     if: always()
