cleanup

diff --git a/.github/workflows/test-workflow.yml b/.github/workflows/test-workflow.yml
--- a/.github/workflows/test-workflow.yml
+++ b/.github/workflows/test-workflow.yml
@@ -14,7 +14,7 @@ jobs:
         run: |
           echo "Running Step 1"
           sleep 30
-      - run: exit 1 # force test failure
+      # - run: exit 1 # force test failure
 
   job-2:
     runs-on: ubuntu-latest
